# Generated by Django 3.1.1 on 2020-09-27 20:38

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='سرفصل')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس سرفصل')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت نمایش')),
                ('position', models.IntegerField(verbose_name='جایگاه')),
            ],
            options={
                'verbose_name': 'دسته بندی صندوق',
                'verbose_name_plural': 'اقلام صندوق',
                'ordering': ['position'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='زیرمجموعه')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('position', models.IntegerField(verbose_name='جایگاه')),
                ('count', models.CharField(choices=[('a', '1'), ('b', '25'), ('c', '50'), ('d', '100')], max_length=1, verbose_name='تعداد هر بسته')),
                ('slug', models.SlugField(default='', max_length=100, unique=True, verbose_name='آدرس')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت نمایش')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing', to='stv.category', verbose_name='سرفصل')),
            ],
            options={
                'verbose_name': 'قیمت گذاری',
                'verbose_name_plural': 'قیمت ها',
                'ordering': ['position'],
            },
        ),
    ]
