# Generated by Django 3.1.1 on 2020-09-28 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchId', models.CharField(max_length=10, unique=True, verbose_name='کد شعبه')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام شعبه')),
                ('tel1', models.CharField(max_length=20, verbose_name='تلفن 1')),
                ('tel2', models.CharField(max_length=20, verbose_name='تلفن 2')),
                ('manager', models.CharField(max_length=100, verbose_name='نام رییس')),
                ('slug', models.SlugField(default='', max_length=100, unique=True, verbose_name='آدرس')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت نمایش')),
            ],
            options={
                'verbose_name': 'شعبه',
                'verbose_name_plural': 'شعبه ها',
            },
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recive', models.IntegerField(verbose_name='دریافتی امروز')),
                ('peyment', models.IntegerField(verbose_name='پرداختی امروز')),
                ('inventory', models.IntegerField(verbose_name='موجودی صندوق')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('slug', models.SlugField(default='', max_length=100, unique=True, verbose_name='آدرس')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashes', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashes', to='stv.branch', verbose_name='شعبه')),
            ],
            options={
                'verbose_name': 'صندوق',
                'verbose_name_plural': 'تاریخچه صندوق',
            },
        ),
    ]
