# Generated by Django 3.1.1 on 2020-09-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stv', '0003_auto_20200929_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='ip',
            field=models.GenericIPAddressField(default='17.20.0.0', verbose_name='آی پی شعبه'),
        ),
    ]
