# Generated by Django 3.1.1 on 2020-09-29 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stv', '0004_auto_20200929_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_author', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_branch', to='stv.branch', verbose_name='شعبه'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='princing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_Pricing', to='stv.pricing', verbose_name='سرفصل'),
        ),
    ]
