# Generated by Django 3.1.1 on 2020-10-02 09:07

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('stv', '0005_auto_20200930_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='date_persian',
            field=django_jalali.db.models.jDateField(auto_now=True, verbose_name='تاریخ شمسی'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.CharField(blank=True, default='رئیس شعبه', max_length=100, verbose_name='نام رییس'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='tel1',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='تلفن 1'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='tel2',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='تلفن 2'),
        ),
        migrations.DeleteModel(
            name='Cash',
        ),
    ]
