# Generated by Django 3.1.1 on 2020-10-02 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stv', '0006_auto_20201002_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recive_day', models.PositiveBigIntegerField(default=0, verbose_name='دریافتی امروز')),
                ('peymen_day', models.PositiveBigIntegerField(default=0, verbose_name='پرداختی امروز')),
                ('inventory_end_day', models.PositiveBigIntegerField(default=0, verbose_name='موجودی صندوق')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('date_persian', django_jalali.db.models.jDateField(auto_now=True, verbose_name='تاریخ شمسی')),
                ('date_per', django_jalali.db.models.jDateField(verbose_name='تاریخ شمسی')),
                ('slug', models.SlugField(default='', max_length=100, unique=True, verbose_name='آدرس')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashes', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashes', to='stv.branch', verbose_name='شعبه')),
            ],
            options={
                'verbose_name': 'صندوق',
                'verbose_name_plural': 'تاریخچه صندوق',
            },
        ),
    ]
