# Generated by Django 3.1.1 on 2020-10-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stv', '0007_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='author',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='slug',
        ),
        migrations.AddField(
            model_name='detail',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد/ قطعه'),
        ),
    ]
