# Generated by Django 3.1.1 on 2020-10-05 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stv', '0008_auto_20201006_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='date_per',
        ),
    ]
