# Generated by Django 3.1.1 on 2020-10-05 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stv', '0009_remove_cash_date_per'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='princing',
            new_name='pricing',
        ),
        migrations.AddField(
            model_name='detail',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='detail',
            name='lastDateEdit',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ویرایش'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد یا قطعه'),
        ),
    ]
