# Generated by Django 3.1.1 on 2020-10-06 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stv', '0010_auto_20201006_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='author',
        ),
        migrations.AddField(
            model_name='detail',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashes', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
    ]
