# Generated by Django 3.1.1 on 2020-10-06 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stv', '0011_auto_20201006_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='profil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_branch', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_branch', to='stv.branch', verbose_name='شعبه'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_detail', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
    ]
