# Generated by Django 3.1.1 on 2020-10-06 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stv', '0012_auto_20201006_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='author',
        ),
        migrations.AlterField(
            model_name='cash',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_detail', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_detail', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
    ]
