# Generated by Django 3.1.1 on 2020-10-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stv', '0013_auto_20201006_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='branch',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
