# Generated by Django 3.1.1 on 2020-10-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stv', '0014_auto_20201006_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='count',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='pricing',
        ),
        migrations.AddField(
            model_name='detail',
            name='daryaft',
            field=models.PositiveBigIntegerField(default=0, verbose_name='دریافتی امروز'),
        ),
        migrations.AddField(
            model_name='detail',
            name='es_1',
            field=models.PositiveBigIntegerField(default=0, verbose_name='1000'),
        ),
        migrations.AddField(
            model_name='detail',
            name='es_10',
            field=models.PositiveBigIntegerField(default=0, verbose_name='10000'),
        ),
        migrations.AddField(
            model_name='detail',
            name='es_100',
            field=models.PositiveBigIntegerField(default=0, verbose_name='100000'),
        ),
        migrations.AddField(
            model_name='detail',
            name='es_2',
            field=models.PositiveBigIntegerField(default=0, verbose_name='2000'),
        ),
        migrations.AddField(
            model_name='detail',
            name='es_20',
            field=models.PositiveBigIntegerField(default=0, verbose_name='20000'),
        ),
        migrations.AddField(
            model_name='detail',
            name='es_5',
            field=models.PositiveBigIntegerField(default=0, verbose_name='5000'),
        ),
        migrations.AddField(
            model_name='detail',
            name='es_50',
            field=models.PositiveBigIntegerField(default=0, verbose_name='50000'),
        ),
        migrations.AddField(
            model_name='detail',
            name='es_far',
            field=models.PositiveIntegerField(default=0, verbose_name='اسکناس فرسوده'),
        ),
        migrations.AddField(
            model_name='detail',
            name='ir_100',
            field=models.PositiveBigIntegerField(default=0, verbose_name='100'),
        ),
        migrations.AddField(
            model_name='detail',
            name='ir_50',
            field=models.PositiveBigIntegerField(default=0, verbose_name='50'),
        ),
        migrations.AddField(
            model_name='detail',
            name='ir_far',
            field=models.PositiveIntegerField(default=0, verbose_name='ایران چک فرسوده'),
        ),
        migrations.AddField(
            model_name='detail',
            name='n_1',
            field=models.PositiveIntegerField(default=0, verbose_name='1000'),
        ),
        migrations.AddField(
            model_name='detail',
            name='n_10',
            field=models.PositiveIntegerField(default=0, verbose_name='10000'),
        ),
        migrations.AddField(
            model_name='detail',
            name='n_2',
            field=models.PositiveIntegerField(default=0, verbose_name='2000'),
        ),
        migrations.AddField(
            model_name='detail',
            name='n_5',
            field=models.PositiveIntegerField(default=0, verbose_name='5000'),
        ),
        migrations.AddField(
            model_name='detail',
            name='pardakht',
            field=models.PositiveBigIntegerField(default=0, verbose_name='پرداختی امروز'),
        ),
        migrations.AddField(
            model_name='detail',
            name='sek_n',
            field=models.IntegerField(default=0, verbose_name='سکه نیم'),
        ),
        migrations.AddField(
            model_name='detail',
            name='sek_r',
            field=models.IntegerField(default=0, verbose_name='سکه ربع'),
        ),
        migrations.AddField(
            model_name='detail',
            name='sek_t',
            field=models.IntegerField(default=0, verbose_name='سکه تمام'),
        ),
        migrations.AddField(
            model_name='detail',
            name='t_ch_25',
            field=models.PositiveIntegerField(default=0, verbose_name='دسته چک 25'),
        ),
        migrations.AddField(
            model_name='detail',
            name='t_ch_50',
            field=models.PositiveIntegerField(default=0, verbose_name='دسته جک 50'),
        ),
        migrations.AddField(
            model_name='detail',
            name='t_ch_hav',
            field=models.PositiveIntegerField(default=0, verbose_name='دسته چک حواله'),
        ),
        migrations.AddField(
            model_name='detail',
            name='t_ch_taz',
            field=models.PositiveIntegerField(default=0, verbose_name='دسته چک تضمین'),
        ),
        migrations.AddField(
            model_name='detail',
            name='t_m',
            field=models.PositiveIntegerField(default=0, verbose_name='تمبرمالیاتی'),
        ),
        migrations.AddField(
            model_name='detail',
            name='t_pard',
            field=models.PositiveIntegerField(default=0, verbose_name='دستور پرداخت'),
        ),
        migrations.AddField(
            model_name='detail',
            name='t_saf',
            field=models.PositiveIntegerField(default=0, verbose_name='تمبرسفته'),
        ),
        migrations.AddField(
            model_name='detail',
            name='t_va',
            field=models.PositiveIntegerField(default=0, verbose_name='تمبر واخواست'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='branch',
            field=models.CharField(default='bmi', max_length=20),
        ),
        migrations.AlterField(
            model_name='detail',
            name='total',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مبلغ کل'),
        ),
    ]
