# Generated by Django 3.1.1 on 2020-10-10 18:28

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('stv', '0017_auto_20201010_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='date_persian',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='detail',
            name='es_1',
            field=models.CharField(default=0, max_length=35, verbose_name='اسکناس 1000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='es_10',
            field=models.CharField(default=0, max_length=35, verbose_name='اسکناس 10000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='es_100',
            field=models.CharField(default=0, max_length=35, verbose_name='اسکناس 100000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='es_2',
            field=models.CharField(default=0, max_length=35, verbose_name='اسکناس 2000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='es_20',
            field=models.CharField(default=0, max_length=35, verbose_name='اسکناس 20000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='es_5',
            field=models.CharField(default=0, max_length=35, verbose_name='اسکناس 5000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='es_50',
            field=models.CharField(default=0, max_length=35, verbose_name='اسکناس 50000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='ir_100',
            field=models.CharField(default=0, max_length=100, verbose_name='ایران چک 100'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='ir_50',
            field=models.CharField(default=0, max_length=100, verbose_name='ایران چک 50'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='n_1',
            field=models.CharField(default=0, max_length=15, verbose_name='نیکل 1000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='n_10',
            field=models.CharField(default=0, max_length=15, verbose_name='نیکل 10000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='n_2',
            field=models.CharField(default=0, max_length=35, verbose_name='نیکل 2000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='n_5',
            field=models.CharField(default=0, max_length=15, verbose_name='نیکل 5000'),
        ),
    ]
