# Generated by Django 3.1.1 on 2020-10-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stv', '0021_auto_20201010_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='total_yesterday',
            field=models.CharField(default=0, max_length=100, verbose_name='مانده دیروز'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='es_1',
            field=models.CharField(default=0, max_length=50, verbose_name='اسکناس 1000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='es_10',
            field=models.CharField(default=0, max_length=50, verbose_name='اسکناس 10000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='es_100',
            field=models.CharField(default=0, max_length=50, verbose_name='اسکناس 100000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='es_2',
            field=models.CharField(default=0, max_length=50, verbose_name='اسکناس 2000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='es_20',
            field=models.CharField(default=0, max_length=50, verbose_name='اسکناس 20000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='es_5',
            field=models.CharField(default=0, max_length=50, verbose_name='اسکناس 5000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='es_50',
            field=models.CharField(default=0, max_length=50, verbose_name='اسکناس 50000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='es_far',
            field=models.CharField(default=0, max_length=50, verbose_name='اسکناس فرسوده'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='n_1',
            field=models.CharField(default=0, max_length=50, verbose_name='نیکل 1000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='n_10',
            field=models.CharField(default=0, max_length=50, verbose_name='نیکل 10000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='n_2',
            field=models.CharField(default=0, max_length=50, verbose_name='نیکل 2000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='n_5',
            field=models.CharField(default=0, max_length=50, verbose_name='نیکل 5000'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='sek_n',
            field=models.CharField(default=0, max_length=50, verbose_name='سکه نیم'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='sek_r',
            field=models.CharField(default=0, max_length=50, verbose_name='سکه ربع'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='sek_t',
            field=models.CharField(default=0, max_length=50, verbose_name='سکه تمام'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='t_ch_25',
            field=models.CharField(default=0, max_length=50, verbose_name='دسته چک 25'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='t_ch_50',
            field=models.CharField(default=0, max_length=50, verbose_name='دسته جک 50'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='t_ch_hav',
            field=models.CharField(default=0, max_length=50, verbose_name='دسته چک حواله'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='t_ch_taz',
            field=models.CharField(default=0, max_length=50, verbose_name='دسته چک تضمین'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='t_m',
            field=models.CharField(default=0, max_length=50, verbose_name='تمبرمالیاتی'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='t_pard',
            field=models.CharField(default=0, max_length=50, verbose_name='دستور پرداخت'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='t_saf',
            field=models.CharField(default=0, max_length=50, verbose_name='تمبرسفته'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='t_va',
            field=models.CharField(default=0, max_length=50, verbose_name='تمبر واخواست'),
        ),
    ]
