# Generated by Django 3.1.1 on 2020-10-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stv', '0023_auto_20201013_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='t_ch_100',
            field=models.CharField(default=0, max_length=50, verbose_name='دسته چک 100'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='t_ch_50',
            field=models.CharField(default=0, max_length=50, verbose_name='دسته چک 50'),
        ),
    ]
