# Generated by Django 3.1.1 on 2020-10-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stv', '0024_auto_20201015_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='total_yesterday',
            field=models.CharField(blank=True, default=0, max_length=100, null=True, verbose_name='مانده دیروز'),
        ),
    ]
