# Generated by Django 3.1.1 on 2020-10-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stv', '0025_auto_20201023_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='n_li',
            field=models.CharField(default=0, max_length=50, verbose_name='نیکل 10000'),
        ),
    ]
