# Generated by Django 3.1.1 on 2020-10-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200907_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch_Id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='branch_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
